name: release
on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
jobs:
  create-release:
    name: create-release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.release.outputs.upload_url }}
      tools_version: ${{ env.TOOLS_VERSION }}
    steps:
      - name: Get the release version from the tag
        shell: bash
        if: env.TOOLS_VERSION == ''
        run: |
          echo "TOOLS_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          echo "version is: ${{ env.TOOLS_VERSION }}"
      - name: Create GitHub release
        id: release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.TOOLS_VERSION }}
          release_name: ${{ env.TOOLS_VERSION }}
          body: See [CHANGELOG.md](https://github.com/zzyandzzy/fit-overlay-cli/blob/master/CHANGELOG.md) for details.
          prerelease: false

  build-release:
    name: build-release
    needs: [ 'create-release' ]
    runs-on: ${{ matrix.os }}
    env:
      CARGO: cargo
      TARGET_FLAGS: ""
      TARGET_DIR: ./target
      RUST_BACKTRACE: 1
    strategy:
      matrix:
        build: [
#          x86_64-linux-gnu,
          x86_64-linux-musl,
#          aarch64-linux-gnu, aarch64-linux-musl,
#          x86_64-apple-darwin, aarch64-apple-darwin,
#          x86_64-pc-windows-msvc, x86_64-pc-windows-gnu, aarch64-pc-windows-msvc,
        ]
        include:
          # Linux (x86_64 & aarch64)
#          - build: x86_64-linux-gnu
#            os: ubuntu-latest
#            target: x86_64-unknown-linux-gnu
          - build: x86_64-linux-musl
            os: ubuntu-latest
            target: x86_64-unknown-linux-musl
#          - build: aarch64-linux-gnu
#            os: ubuntu-latest
#            target: aarch64-unknown-linux-gnu
#          - build: aarch64-linux-musl
#            os: ubuntu-latest
#            target: aarch64-unknown-linux-musl
#
#          # macOS (x86_64 & aarch64)
#          - build: x86_64-apple-darwin
#            os: macos-latest
#            target: x86_64-apple-darwin
#          - build: aarch64-apple-darwin
#            os: macos-latest
#            target: aarch64-apple-darwin

          # Windows (x86_64 & aarch64)
#          - build: x86_64-pc-windows-msvc
#            os: windows-2022
#            target: x86_64-pc-windows-msvc
#          - build: x86_64-pc-windows-gnu
#            os: ubuntu-22.04
#            target: x86_64-pc-windows-gnu
#          - build: aarch64-pc-windows-msvc
#            os: windows-2022
#            target: aarch64-pc-windows-msvc

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          submodules: true

      - name: Install musl tools
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install -y musl-tools && sudo apt-get install -y libssl-dev && sudo apt-get install -y python3 && sudo apt-get install -y curl

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          target: ${{ matrix.target }}

      - name: Use Cross
        shell: bash
        run: |
          cargo install cross --git https://github.com/cross-rs/cross
          echo "CARGO=cross" >> $GITHUB_ENV
          echo "TARGET_FLAGS=--target ${{ matrix.target }}" >> $GITHUB_ENV
          echo "TARGET_DIR=./target/${{ matrix.target }}" >> $GITHUB_ENV

      - name: Show command used for Cargo
        run: |
          echo "cargo command is: ${{ env.CARGO }}"
          echo "target flag is: ${{ env.TARGET_FLAGS }}"
          echo "target dir is: ${{ env.TARGET_DIR }}"

      - name: Build release binary
        run: ${{ env.CARGO }} build --verbose --release ${{ env.TARGET_FLAGS }}

      - name: Build archive
        shell: bash
        run: |
          staging="fit-overlay-cli-${{ needs.create-release.outputs.tools_version }}-${{ matrix.target }}"
          mkdir -p "$staging"
          if [ "${{ matrix.os }}" = "windows-2022" ] || [ "${{ matrix.build }}" = "x86_64-pc-windows-gnu" ]; then
            cp "target/${{ matrix.target }}/release/fit-overlay-cli.exe" "$staging/"
            cp "js/chart.js" "$staging/"
            cp "js/set_option.js" "$staging/"
            7z a -tzip "$staging.zip" "$staging"
            echo "ASSET=$staging.zip" >> $GITHUB_ENV
          else
            cp "target/${{ matrix.target }}/release/fit-overlay-cli" "$staging/"
            cp "js/chart.js" "$staging/"
            cp "js/set_option.js" "$staging/"
            tar czf "$staging.tar.gz" "$staging"
            echo "ASSET=$staging.tar.gz" >> $GITHUB_ENV
          fi

      - name: Upload release archive
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ${{ env.ASSET }}
          asset_name: ${{ env.ASSET }}
          asset_content_type: application/octet-stream